android_library(
    name = "instrumentation",
    srcs = glob(["*.java"]),
    manifest = "AndroidManifest.xml",
    visibility = ["//src/test/java/org/matthewtodd/perquackey/android/application:__pkg__"],
)
