android_library(
    name = "main",
    srcs = glob(["*.java"]),
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
    visibility = ["//src/test/java/org/matthewtodd/perquackey/android/application:__pkg__"],
)
