android_binary(
    name = "android",
    srcs = glob(["*.java"]),
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
    deps = ["//src/main/java/org/matthewtodd/perquackey/common:common"],
    visibility = ["//visibility:public"],
)
