#!/usr/bin/env ruby
require File.join(File.dirname(__FILE__), '..', 'config', 'boot')

libs =  " -r #{RAILS_ROOT}/config/environment"
libs << " -r #{RAILS_ROOT}/lib/perquackey/console"

exec "irb #{libs} --simple-prompt"
