android_binary(
    name = "application",
    manifest = "AndroidManifest.xml",
    deps = [
        "//src/main/java/org/matthewtodd/perquackey/android/main:main",
        "//src/test/java/org/matthewtodd/perquackey/android/instrumentation:instrumentation",
    ],
    visibility = ["//src/test:__pkg__"],
)
