alias(
  name = "android",
  actual = "//src/main/java/org/matthewtodd/perquackey/android:android",
)

alias(
  name = "common",
  actual = "//src/main/java/org/matthewtodd/perquackey/common:common",
)
